; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool on Tue Feb 06 2018 17:00:38 GMT+0100 (CET)
G91               ; relative positioning
G1 Z5 F6000       ; lift Z relative to current position
G1 S1 Y-365 F1800 ; move quickly to Y axis endstop and stop there (first pass)
G1 Y5 F6000       ; go back a few mm
G1 S1 Y-365 F360  ; move slowly to Y axis endstop once more (second pass)
G1 Z-5 F6000      ; lower Z again
G90               ; absolute positioning